### ISSUE TITLE
Idiomatic GO client

### ISSUE THREAD

**Issue by TamalSaha** [ovh/go-ovh#10]
We are interested in using OVH api to create VMs using the GO client. But I saw that OVH's client library does not really wrap all the api methods and objects in an idiomatic GO client. By looking at the json schema docs, it seemed like it should be possible to write an auto generated library. Does OVH has any plans to do that? Is OVH using any api spec language. I checked swagger 2.0. It did not work.

Thanks.

**Comment by yadutaf** [comment]
Hello @TamalSaha,

Thanks for your interest in developing for OVH APIs. The API format is OVH specific and is not compatible with swagger as of yet.

This project is an API wrapper. It is designed to be a tiny wrapper around the the API authentication and request signing part which. We have no plan to provide a full featured idiomatic client for the OVH client.

This said, which parts of the APIs would you be interested in if we were to start implementing an API subset? If you are targeting the "Cloud" API, you may find a subset in https://github.com/yadutaf/docker-machine-driver-ovh/blob/master/api.go.

**Comment by tamalsaha** [comment]
@yadutaf / @cygy, we have published a idiomatic Go client for OVH apis https://github.com/appscode/go-ovh.
