### ISSUE TITLE
Simple POST example

### ISSUE THREAD

**Issue by purplefish32** [ovh/go-ovh#16]
Hello, 
I have been trying in vain to use go-ovh to make a new CNAME record via the OVH API

I have taken a simple first example :
POST to : /domain/zone/mydomain.com/refresh

I have tried both : 

```
Client.Post("/domain/zone/mydomain.com/refresh", "", "")
```

and

```
Client.Post("/domain/zone/mydomain.com/refresh", "{}", "{}")
```

But each time I am greeted with : Error 400: "Invalid JSON received"

Not sure if this is a bug or my mis interpritation of how to use the lib.

Could you please point me in the right direction.

Thank you in advance.

**Comment by purplefish32** [comment]
I think have found the error -> nil instrad of "{}"
Sorry for my noobishness

**Comment by yadutaf** [comment]
No worry :) Is there any improvement to the doc / example we could have done to spare you this research ?

**Comment by purplefish32** [comment]
@yadutaf 
Yeah, I am really struggling, (first go app for me) I still cant seem to do a simple POST request, I keep getting : Error 400: "Invalid JSON received" or a missing field in my json

```
var jsonStr =[]byte(`{"target":"mytargetdomainname.com.","fieldType":"CNAME","subDomain":"mysubdomain"}`)
request := Client.Post("/domain/zone/mydomain.com/record", string(jsonStr), nil)
```

A simple post example in the docs would be a lot of help.

**Comment by yadutaf** [comment]
Thanks for the feedback! In the meantime, you can have a look at https://github.com/yadutaf/docker-machine-driver-ovh/blob/master/api.go

**Comment by purplefish32** [comment]
@yadutaf Thanks, that was a huge help for me, you rock !
