### ISSUE TITLE
OVH US documentation

### ISSUE THREAD

**Issue by gregdel** [ovh/go-ovh#24]
We should add the doc for the US API

**Comment by gregdel** [comment]
That's how the links should look like according to the other endpoints (eu and ca), but they are not working for now
- **Documentation**: https://us.api.ovh.com/
- **Community support**: api-subscribe@ml.ovh.net
- **Console**: https://us.api.ovh.com/console
- **Create application credentials**: https://us.api.ovh.com/createApp/
- **Create script credentials** (all keys at once): https://us.api.ovh.com/createToken/

**Comment by geoffreybauduin** [comment]
Doc/Console/Application credentials and script credentials are under https://api.ovh.us website for now.

https://api.ovh.us
https://api.ovh.us/console/
https://api.ovh.us/createApp/
https://api.ovh.us/createToken/

**Comment by gregdel** [comment]
On the last three links, if you remove the `/` at the end, you're redirected to a non working backend...
