### ISSUE TITLE
No error in case of bad credentials

### ISSUE THREAD

**Issue by seospace** [ovh/go-ovh#26]
If you provide bad credentials (appkey/secret/consumerkey) NewClient does not return an error.

**Comment by gregdel** [comment]
Hi, we don't check the validity of your credentials until you try to use them. We can't know in advance the calls you're gonna make on the API, if your token is expired or if you have the rights to access the path on which you're gonna make the call.

**Comment by seospace** [comment]
@gregdel good point thank you
