### ISSUE TITLE
user: Current not implemented on linux/amd64 when cross compilation

### ISSUE THREAD

**Issue by thbkrkr** [ovh/go-ovh#29]
go-ovh uses user.Current() to get the current user home directory (https://github.com/ovh/go-ovh/blob/master/ovh/configuration.go#L22).

os/user relies on cgo, and cgo is disabled for cross compiling thus it can be an issue to use go-ovh with cross compilation.

Currently I encounter this issue with github.com/terraform-providers/terraform-provider-ovh .

I propose to implement a workaround by reading the environment variable $HOME if an error occurred by calling user.Current().

**Comment by gregdel** [comment]
Or we could use the widely used homedir lib: https://github.com/mitchellh/go-homedir
It solves this issue, enabling multi arch and multi platform support, but it would mean adding an external dependency to this project... 
@thbkrkr what do you think ?

**Comment by thbkrkr** [comment]
I also thought about using mitchellh/go-homedir but I think it's overkilled and just reading $HOME is simpler and will work in 99,95% of cases.

**Comment by gregdel** [comment]
I agree ! Waiting for your PR <3
