### ISSUE TITLE
Pull request Travis CI config error

### ISSUE THREAD

**Issue by niltonkummer** [ovh/go-ovh#33]
When I submit the Pull Request, Travis CI cannot build because the golint generate a error when run it: 

`$ gimme version
v1.3.0
$ go version
go version go1.6 linux/amd64
go.env
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.6.linux.amd64"
GOTOOLDIR="/home/travis/.gimme/versions/go1.6.linux.amd64/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
before_install.1
4.75s$ go get github.com/axw/gocov/gocov
before_install.2
2.38s$ go get github.com/mattn/goveralls
2.34s$ go get github.com/golang/lint/golint
# golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:77: undefined: io.SeekCurrent
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:80: undefined: io.SeekCurrent
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:156: undefined: io.SeekCurrent
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:187: r.declReader.Reset undefined (type bytes.Reader has no field or method Reset)
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:226: r.declReader.Reset undefined (type bytes.Reader has no field or method Reset)
The command "go get github.com/golang/lint/golint" failed and exited with 2 during .
Your build has been stopped.`

I would like make a pull request of a bugfix.

**Comment by gregdel** [comment]
This should be fixed now
