### ISSUE TITLE
Panic if client creation has failed

### ISSUE THREAD

**Issue by PaulB2Code** [ovh/go-ovh#46]
Hi, 

We add an issue when a client is not create but we still want to try a request. 

It goes to panic : 
/opt/code/gocode/src/github.com/ovh/go-ovh/ovh/ovh.go:282 +0x180
github.com/ovh/go-ovh/ovh.(*Client).CallAPIWithContext(0x0, 0x169c200, 0xc0000a2040, 0x15bec22, 0x4, 0xc0008c1ea0, 0xa, 0x1578140, 0xc0043ceb80, 0x14fd520, ...)

We patch it with this:

	if c == nil {
		return nil, fmt.Errorf("Client is not valid")
	}

It allows to return an error without failing. 

Looking you're feedback. 

in ovh.go
`
// NewRequest returns a new HTTP request
func (c *Client) NewRequest(method, path string, reqBody interface{}, needAuth bool) (*http.Request, error) {
	var body []byte
	var err error

	if reqBody != nil {
		body, err = json.Marshal(reqBody)
		if err != nil {
			return nil, err
		}
	}
	**if c == nil {
		return nil, fmt.Errorf("Client is not valid")
	}**
	target := fmt.Sprintf("%s%s", c.endpoint, path)
	req, err := http.NewRequest(method, target, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}

	// Inject headers
	if body != nil {
		req.Header.Add("Content-Type", "application/json;charset=utf-8")
	}
	req.Header.Add("X-Ovh-Application", c.AppKey)
	req.Header.Add("Accept", "application/json")

	// Inject signature. Some methods do not need authentication, especially /time,
	// /auth and some /order methods are actually broken if authenticated.
	if needAuth {
		timeDelta, err := c.TimeDelta()
		if err != nil {
			return nil, err
		}

		timestamp := getLocalTime().Add(-timeDelta).Unix()

		req.Header.Add("X-Ovh-Timestamp", strconv.FormatInt(timestamp, 10))
		req.Header.Add("X-Ovh-Consumer", c.ConsumerKey)

		h := sha1.New()
		h.Write([]byte(fmt.Sprintf("%s+%s+%s+%s%s+%s+%d",
			c.AppSecret,
			c.ConsumerKey,
			method,
			getEndpointForSignature(c),
			path,
			body,
			timestamp,
		)))
		req.Header.Add("X-Ovh-Signature", fmt.Sprintf("$1$%x", h.Sum(nil)))
	}

	// Send the request with requested timeout
	c.Client.Timeout = c.Timeout

	return req, nil
}
`

**Comment by geoffreybauduin** [comment]
Hello, the "NewClient" method (https://godoc.org/github.com/ovh/go-ovh/ovh#NewClient) returns an error if it was not able to be correctly initialized.

Can you copy / paste here an extract of your code to help you investigate further?

**Comment by rbeuque74** [comment]
This issue is inactive, feel free to re-open if it still applies.
