### ISSUE TITLE
Inconsistency between documentation and code for config discovery

### ISSUE THREAD

**Issue by Lebvanih** [ovh/go-ovh#71]
Hello,

I noticed that in a "recent" commit this line changed from /etc/ovh.conf to /etc/ovh.com https://github.com/ovh/go-ovh/blob/master/ovh/configuration.go#L14. Is this on purpose or just a typo when remaking the code around it? 

This comes from the following commit: https://github.com/ovh/go-ovh/commit/39b6ccfa1451f02114c45cd6abce2d0879a4da4f

The readme.md still mention /etc/ovh.conf https://github.com/ovh/go-ovh/blob/master/README.md?plain=1#L96

I will adapt our code to use the other name for now, but it would be nice to have this clarified/fixed.

Kr,

**Comment by deathiop** [comment]
Hello @Lebvanih ,

This is not intended, don't update your code, I will push a fix ASAP.

**Comment by deathiop** [comment]
Fixed in #72.
`go get github.com/ovh/go-ovh@v1.4.2` :)
