### ISSUE TITLE
OVH client expose endpoint

### ISSUE THREAD

**Issue by Azanul** [ovh/go-ovh#73]
I need to access the endpoint of a created client. Without it I've to pass the endpoint through my functions separately.

This can be done in a backward compatible way by adding a method to get the endpoint.

**Comment by deathiop** [comment]
Hello @Azanul,

May you please elaborate on your exact need? Maybe with a small example of what you fail to achieve with go-ovh in its current state?

**Comment by Azanul** [comment]
Hi @deathiop,
I'm creating an integration to [Komiser](https://github.com/tailwarden/komiser)
I need endpoint https://github.com/ovh/go-ovh/blob/a1158c3496c00fc9dabeb6ca48e3efdfeed9ffd1/ovh/ovh.go#L67. I can achieve the same by passing endpoint separately along with the client but it'd be better if endpoint was exposed from the client itself.

**Comment by deathiop** [comment]
You can upgrade to v1.4.3 which allow `client.Endpoint()` as a getter for you need.
See #74 
Have a nice day!
