### ISSUE TITLE
Feature request: add support for oauth2 access token authentication

### ISSUE THREAD

**Issue by csandanov** [ovh/go-ovh#76]
Since OVH [supports OAuth2](https://help.ovhcloud.com/csm/en-manage-service-account?id=kb_article_view&sysparm_article=KB0059343) it would be great if I could use this sdk with authorization via oauth2 access token.

**Comment by rbeuque74** [comment]
Hello @csandanov ,
I started an implementation of your request here: #79 

I hope to merge this one during January.

Have a great day
Romain

**Comment by csandanov** [comment]
Thank you!
