### ISSUE TITLE
Adding a new resource for mgmt

### ISSUE THREAD

**Issue by purpleidea** [ovh/go-ovh#85]
Hi, my name is James from the https://github.com/purpleidea/mgmt/ project. We're interested in building OVH resources for mgmt. We had a few questions:

1. Is there a good technical contact we can reach for API issues and other discussions?
2. Is anyone at OVH interested in contributing to the project?
3. Do you have any free developer accounts you can give us access to?
3b. Alternatively, if there is a way to cap spending so that a credit-card backed account that we have blocks any erroneous API call that would charge us more than $N for example. (While developing.)

Lastly, the biggest missing thing that I've noticed when browsing the OVH API's is that there aren't any event-based options. We have a short guide to building API's which might better explain what I am looking for. It can be seen here: https://github.com/purpleidea/mgmt/blob/master/docs/service-guide.md#events

Thank you for your time!

**Comment by deathiop** [comment]
Hi James,

You can reach out for API people at OVHcloud at api@ml.ovh.net; to subscribe to this mailing list, send an email to api-subscribe@ml.ovh.net.
You can also join this discord channel: https://discord.com/channels/850031577277792286/1063409229781811251.

To answer your other questions, `mgmt` is not a tool we are aware of and, therefore, there is no plan to contribute as of now.
We do not have any special features dedicated to the development using our APIs, meaning you'll have to use a standard account. We don't have a way to cap the use of a payment mean.

Have a nice day,

- A

**Comment by purpleidea** [comment]
Merci beaucoup pour votre message et les informations !
